"""initial schema: sessions, problems, analyses, hints

Revision ID: 678ae874da67
Revises: 
Create Date: 2026-10-06 21:48:23.921396
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '678ae874da67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('test_cases', sa.JSON(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('solution_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('times_attempted', sa.Integer(), nullable=False),
    sa.Column('average_completion_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coding_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('problem_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_code', sa.Text(), nullable=True),
    sa.Column('hint_level_preference', sa.Integer(), nullable=False),
    sa.Column('screen_mode_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_analysis_enabled', sa.Boolean(), nullable=False),
    sa.Column('total_hints_requested', sa.Integer(), nullable=False),
    sa.Column('errors_fixed', sa.Integer(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_sessions_id'), 'coding_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_coding_sessions_session_token'), 'coding_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_coding_sessions_user_id'), 'coding_sessions', ['user_id'], unique=False)
    op.create_table('code_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('analyzer_name', sa.String(length=100), nullable=False),
    sa.Column('code_snapshot', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['coding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_analyses_code_hash'), 'code_analyses', ['code_hash'], unique=False)
    op.create_index(op.f('ix_code_analyses_id'), 'code_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_code_analyses_session_id'), 'code_analyses', ['session_id'], unique=False)
    op.create_table('mentor_hints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('hint_category', sa.String(length=100), nullable=False),
    sa.Column('hint_text', sa.Text(), nullable=False),
    sa.Column('hint_type', sa.String(length=50), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('user_reaction', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=True),
    sa.Column('safety_approved', sa.Boolean(), nullable=False),
    sa.Column('contains_solution', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['code_analyses.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['coding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_hints_analysis_id'), 'mentor_hints', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_mentor_hints_id'), 'mentor_hints', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_hints_session_id'), 'mentor_hints', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentor_hints_session_id'), table_name='mentor_hints')
    op.drop_index(op.f('ix_mentor_hints_id'), table_name='mentor_hints')
    op.drop_index(op.f('ix_mentor_hints_analysis_id'), table_name='mentor_hints')
    op.drop_table('mentor_hints')
    op.drop_index(op.f('ix_code_analyses_session_id'), table_name='code_analyses')
    op.drop_index(op.f('ix_code_analyses_id'), table_name='code_analyses')
    op.drop_index(op.f('ix_code_analyses_code_hash'), table_name='code_analyses')
    op.drop_table('code_analyses')
    op.drop_index(op.f('ix_coding_sessions_user_id'), table_name='coding_sessions')
    op.drop_index(op.f('ix_coding_sessions_session_token'), table_name='coding_sessions')
    op.drop_index(op.f('ix_coding_sessions_id'), table_name='coding_sessions')
    op.drop_table('coding_sessions')
    op.drop_table('problems')
    # ### end Alembic commands ###
