"""
In-process typed async event bus for decoupled communication.
"""

import asyncio
from typing import Any, Callable, Dict, List, Type, TypeVar, Generic
from dataclasses import dataclass
from datetime import datetime, timezone
import logging

logger = logging.getLogger(__name__)

T = TypeVar('T')


@dataclass
class Event:
    """Base event class with timestamp and correlation ID."""
    timestamp: datetime = None
    correlation_id: str = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now(timezone.utc)


@dataclass
class SnapshotReceived(Event):
    """Code snapshot received from frontend."""
    session_id: str
    sequence: int
    code: str
    language: str
    source: str  # "editor" or "screen"


@dataclass
class DiagnosticsGenerated(Event):
    """Analysis completed with diagnostics."""
    session_id: str
    sequence: int
    diagnostics: List[Any]  # Will be proper Diagnostic objects
    analysis_time_ms: float


@dataclass
class HintRequested(Event):
    """Mentor should generate a hint."""
    session_id: str
    issue_id: str
    level: int


@dataclass
class HintGenerated(Event):
    """Hint generated by mentor."""
    session_id: str
    issue_id: str
    level: int
    hint: str
    confidence: float


EventHandler = Callable[[Any], None]


class EventBus:
    """Simple in-process event bus with async handlers."""

    def __init__(self):
        self._handlers: Dict[Type, List[EventHandler]] = {}
        self._lock = asyncio.Lock()

    def subscribe(self, event_type: Type[T], handler: Callable[[T], None]):
        """Subscribe to events of a specific type."""
        if event_type not in self._handlers:
            self._handlers[event_type] = []
        self._handlers[event_type].append(handler)

        logger.debug("Subscribed handler for event", extra={
            "event_type": event_type.__name__,
            "handler": handler.__name__
        })

    async def publish(self, event: Event):
        """Publish an event to all subscribers."""
        event_type = type(event)
        handlers = self._handlers.get(event_type, [])

        if not handlers:
            logger.debug("No handlers for event", extra={
                "event_type": event_type.__name__
            })
            return

        logger.debug("Publishing event", extra={
            "event_type": event_type.__name__,
            "handler_count": len(handlers),
            "correlation_id": getattr(event, 'correlation_id', None)
        })

        # Run all handlers concurrently
        async def safe_handler(handler, event):
            try:
                if asyncio.iscoroutinefunction(handler):
                    await handler(event)
                else:
                    handler(event)
            except Exception as e:
                logger.exception("Event handler failed", extra={
                    "event_type": event_type.__name__,
                    "handler": handler.__name__,
                    "error": str(e)
                })

        await asyncio.gather(*[
            safe_handler(handler, event) for handler in handlers
        ], return_exceptions=True)